;(function(){'use strict';var bn=MugineRequire("Utils/Module"),cn=MugineRequire("Text/TextField"),dn=MugineRequire("Utils/Plugin"),en=MugineRequire("Geom/Color");function fn(){fn.j.constructor.apply(this,arguments);this.Xi="";this.Dh=this.Yi=null}bn.extend(fn,cn);fn.prototype.L="Text";
fn.Jb=function(a,b){function c(){c.j.constructor.apply(this,arguments);this.Xi=f;this.Dh=g;if(e.hintColor)this.Yi=en.parse(e.hintColor);else{var a=this.Hd.ed.clone();a.Ul(.5);this.Yi=a}this.$a("")}var d=cn.Jb(a,b);bn.extend(d,fn);var e=a.param,f=e.textContent,g=e.inputType;bn.extend(c,d);return c};bn.H("Text.InputBox",fn);dn.Zd(2031,fn);var gn=MugineRequire("Utils/Module"),hn=MugineRequire("Utils/Browser"),jn=MugineRequire("Render/RenderObjectTextField"),ln=MugineRequire("Render/StyleSheet"),mn=MugineRequire("Utils/Plugin"),nn=MugineRequire("Render/RenderObject");function on(){on.j.constructor.apply(this,arguments)}gn.extend(on,jn);nn.Ra=function(a){return nn.ig[a]};var pn=on.prototype;
pn.Oa=function(){var a=this.c,b=this.it(),c=a.Hd,d=a.u.wa,e="";d.nb&&0<d.nb.ga&&(e+=hn.prefix.f+"text-stroke:"+d.Nb/1+"px "+d.nb.Eb()+";");c=ln.V("position: absolute; outline: none; padding: 0; background: transparent; border-radius: 0; border: 0; width: "+a.ta+"px; height: "+a.sa+"px;"+hn.prefix.f+"transform-origin: left top;"+hn.prefix.f+"appearance:none;"+hn.prefix.f+"user-select: initial;"+e+"font-family: "+c.Nj+";text-align: "+c.Zg+";color: "+c.ed.Eb()+";font-size: "+d.Db+"px;"+(c.Dj?"font-weight: bold;":
"")+(c.fm?"text-decoration: underline;":"")+(c.$j?"font-style: italic;":"")+(a.Jd?"cursor: pointer;":""));this.va.push(c);this.ld=c;e="color: "+a.Yi.Eb();if(hn.$h.fF)var f=c+"::-webkit-input-placeholder";else hn.$h.CD?f=19>parseInt(hn.$h.version)?c+":-moz-placeholder":c+"::-moz-placeholder":hn.$h.nw&&(f=c+":-ms-input-placeholder");ln.V(f,e);"textArea"==a.Dh?(e="","0"==b.lineHeight?e="normal":b.lineHeight&&(e="line-height:"+b.lineHeight+"px;"),this.fa='<textArea ondragstart="return false;" data-type="input-box" data-mid="'+
a.o+'"'+(a.W?' data-guid="'+a.W+'"':"")+' class="{{className}}" placeholder="'+unescape(a.Xi)+'"style="'+e+'"></textArea>'):(e=(b=0<=["date","time"].indexOf(a.Dh))?"value":"placeholder",f=unescape(a.Xi),b&&f&&a.$a(f),this.fa='<input ondragstart="return false;" data-type="input-box" data-mid="'+a.o+'"'+(a.W?' data-guid="'+a.W+'"':"")+' class="{{className}}" type="'+a.Dh+'" '+e+'="'+f+'"/>')};pn.Cu=function(){return this.Z().tagName};var qn=null;
pn.Sy=function(){var a=document.getElementById("_AnalogInput"),b=document.getElementById("_AnalogArea"),c=nn.Ra(0).Z();a||(a=document.createElement("span"),a.style.zIndex="10",a.style.position="absolute",a.style.left="-9999px",a.id="_AnalogInput",c.appendChild(a));b||(b=document.createElement("textarea"),b.style.zIndex="10",b.style.position="absolute",b.style.left="-9999px",b.id="_AnalogArea",b.style.height="0",c.appendChild(b))};
pn.Qb=function(){on.j.Qb.apply(this,arguments);this.Z().addEventListener("change",this.Iy.bind(this));this.Z().addEventListener("input",this.eB.bind(this));this.Z().addEventListener("focus",this.fz.bind(this));this.Z().addEventListener("click",this.Ny.bind(this));this.Sy()};pn.it=function(){var a=this.c.A.param;return{importLimit:a.importLimit,limitCharset:a.limitCharset,lengthItem:a.lengthItem,lengthLimit:a.lengthLimit,lineHeight:a.inputLineheight}};
pn.gB=function(a){var b=this.Z(),c=this.it(),d=b.value;if(!c.importLimit&&!c.lengthItem||"0"==c.importLimit&&"0"==c.lengthItem)a&&a(d);else{var e=!1,f=document.getElementById("_AnalogInput"),g=document.getElementById("_AnalogArea"),h=this.Cu();if(c.importLimit)switch(c.importLimit){case "1":var k=d.match(/[\u4e00-\u9fa5]/gi)||[],k=k.join("");k!=d&&(d=k,Mugeda.messageBox("\u8bf7\u53ea\u8f93\u5165\u4e2d\u6587\u3002",null,function(){a&&a(d)}),e=!0);break;case "2":k=d.match(/[a-z]/gi)||[];k=k.join("");
k!=d&&(d=k,Mugeda.messageBox("\u8bf7\u53ea\u8f93\u5165\u82f1\u6587\u3002",null,function(){a&&a(d)}),e=!0);break;case "4":if(c.limitCharset){k=c.limitCharset;c.limitCharset+="\n";for(var l=!1,n=0;n<d.length;)-1==c.limitCharset.indexOf(d[n])?(d=d.replace(d[n],""),l=!0):n++;l&&(Mugeda.messageBox("\u8bf7\u53ea\u8f93\u5165\u5982\u4e0b\u5b57\u7b26\uff1a\uff08"+k+"\uff09",null,function(){a&&a(d)}),e=!0)}}if(!e)if("INPUT"==h){if(d=d.replace(/\s/gi,"&nbsp;"),f.innerHTML=d,d=d.replace(/\&nbsp;/g," "),g=b.offsetWidth,
b=f.offsetWidth,c.lengthItem&&0!=c.lengthItem)switch(c.lengthItem){case "1":b=parseInt(c.lengthLimit);c.lengthLimit&&d.length>b&&(d=d.substr(0,b),f.innerHTML=d,Mugeda.messageBox("\u6700\u591a\u53ef\u4ee5\u8f93\u5165 "+b+" \u4e2a\u5b57\u7b26\u3002",null,function(){a&&a(d)}),e=!0);break;case "2":if(b>g)for(c=0;c<d.length;c++)b>g&&(d=d.substring(0,d.length-1),f.innerHTML=d,b=f.offsetWidth,Mugeda.messageBox("\u8f93\u5165\u8d85\u51fa\u4e86\u5141\u8bb8\u7684\u957f\u5ea6\u8303\u56f4\u3002",null,function(){a&&
a(d)}),e=!0)}}else if("TEXTAREA"==h&&c.lengthItem&&0!=c.lengthItem)switch(c.lengthItem){case "1":b=parseInt(c.lengthLimit);c.lengthLimit&&d.length>b&&(d=d.substr(0,b));g.value=d;break;case "2":g.value=d,f=parseInt(window.getComputedStyle(b).lineHeight)||39,Math.round(g.scrollHeight/f)>=Math.round(b.scrollHeight/f)?g.value=qn:qn=d}!e&&a&&a(d)}};pn.eB=function(){};pn.Ny=function(){var a=this.Z();document.activeElement!=a&&a.focus()};
pn.fz=function(){var a=this.Z(),b=this.Cu(),c=document.getElementById("_AnalogInput"),d=document.getElementById("_AnalogArea"),e=window.getComputedStyle(a);"INPUT"==b?(c.style.font=e.font,c.style.transform=e.transform,c.style.left="-9999px"):"TEXTAREA"==b&&(d.style.font=e.font,d.style.transform=e.transform,d.style.overflowY="hidden",d.style.width=a.offsetWidth+"px",d.style.padding=0,d.style.border="none",d.style.left="-9999px")};
pn.Iy=function(){var a=this,b=a.Z(),c=b.value;a.gB(function(d){c!=d&&(b.value=d,b.focus(),b.select());a.c.$a(d)})};pn.s=function(){var a=this.Z();if(document.activeElement==a){var b=a.getBoundingClientRect(),a=b.top,c=b.bottom,b=gn.Dk(),a=(a+c)/2,b=b.height,c=this.c.Va().R.Pf;if(0>a||a>b)c.style.cssText+=hn.prefix.f+"transform: translateY(-200px);"}};pn.ua=function(a,b,c){var d=this.c;on.j.constructor.j.ua.apply(this,arguments);d=d.ub();d!=this.ha.value&&(this.ha.value=d)};mn.$d(2031,on);
})();